### ISSUE TITLE
Design Document

### ISSUE THREAD

**Issue by LibertyVinova** [VinovaHcmInternshipiOS/vForum#3]
- [x] Forum usecase.
- [x] Memory usecase
- [x] Event usecase
- [x] Notification usecase

**Comment by tiengtructiengdong** [comment]
[Use case - Event.docx](https://github.com/VinovaHcmInternshipiOS/vForum/files/5225104/Use.case.-.Event.docx)

**Comment by tiengtructiengdong** [comment]
[Use case - Feed.docx](https://github.com/VinovaHcmInternshipiOS/vForum/files/5225109/Use.case.-.Feed.docx)

**Comment by tiengtructiengdong** [comment]
[Use case - Forum.pdf](https://github.com/VinovaHcmInternshipiOS/vForum/files/5225125/Use.case.-.Forum.pdf)

**Comment by tiengtructiengdong** [comment]
[Use case - Notification.pdf](https://github.com/VinovaHcmInternshipiOS/vForum/files/5229183/Use.case.-.Notification.pdf)
